CRITICAL - 2024-08-01 03:35:08 --> Error: Call to undefined function set_value()
[Method: POST, Route: cadastro]
in APPPATH/Views/cadastro.php on line 17.
 1 SYSTEMPATH/View/View.php(234): include()
 2 SYSTEMPATH/View/View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH/Common.php(1171): CodeIgniter\View\View->render('cadastro', [], true)
 4 APPPATH/Controllers/AuthController.php(39): view('cadastro', [])
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-01 03:35:18 --> Error: Call to undefined function set_value()
[Method: GET, Route: cadastro]
in APPPATH/Views/cadastro.php on line 17.
 1 SYSTEMPATH/View/View.php(234): include()
 2 SYSTEMPATH/View/View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH/Common.php(1171): CodeIgniter\View\View->render('cadastro', [], true)
 4 APPPATH/Controllers/AuthController.php(39): view('cadastro', [])
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-01 03:35:20 --> Error: Call to undefined function set_value()
[Method: GET, Route: cadastro]
in APPPATH/Views/cadastro.php on line 17.
 1 SYSTEMPATH/View/View.php(234): include()
 2 SYSTEMPATH/View/View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH/Common.php(1171): CodeIgniter\View\View->render('cadastro', [], true)
 4 APPPATH/Controllers/AuthController.php(39): view('cadastro', [])
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-01 03:48:09 --> Error: Call to undefined function set_value()
[Method: GET, Route: cadastro]
in APPPATH/Views/cadastro.php on line 12.
 1 SYSTEMPATH/View/View.php(234): include()
 2 SYSTEMPATH/View/View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH/Common.php(1171): CodeIgniter\View\View->render('cadastro', [], true)
 4 APPPATH/Controllers/AuthController.php(12): view('cadastro')
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->mostrarPaginaCadastro()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-01 03:49:37 --> ErrorException: Array to string conversion
[Method: POST, Route: cadastro]
in APPPATH/Controllers/AuthController.php on line 22.
 1 APPPATH/Controllers/AuthController.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', '/Applications/MAMP/htdocs/zero/app/Controllers/AuthController.php', 22)
 2 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
 3 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 4 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-01 03:52:31 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'mamp'@'localhost' (using password: NO) in /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'mamp', Object(SensitiveParameterValue), 'zero', 3306, '', 0)
#1 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/zero/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Applications/MAMP/htdocs/zero/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Applications/MAMP/htdocs/zero/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Applications/MAMP/htdocs/zero/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#7 /Applications/MAMP/htdocs/zero/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 /Applications/MAMP/htdocs/zero/app/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save(Array)
#9 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
#10 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/zero/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/zero/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Applications/MAMP/htdocs/zero/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/zero/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 /Applications/MAMP/htdocs/zero/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#4 /Applications/MAMP/htdocs/zero/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#5 /Applications/MAMP/htdocs/zero/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#6 /Applications/MAMP/htdocs/zero/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#7 /Applications/MAMP/htdocs/zero/app/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save(Array)
#8 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
#9 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/zero/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/zero/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /Applications/MAMP/htdocs/zero/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-08-01 03:52:31 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: POST, Route: cadastro]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 3 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 7 APPPATH/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
 9 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-01 03:52:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'zero', 3306, '', 0)
#1 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/zero/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Applications/MAMP/htdocs/zero/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Applications/MAMP/htdocs/zero/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Applications/MAMP/htdocs/zero/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#7 /Applications/MAMP/htdocs/zero/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 /Applications/MAMP/htdocs/zero/app/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save(Array)
#9 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
#10 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/zero/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/zero/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Applications/MAMP/htdocs/zero/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/zero/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 /Applications/MAMP/htdocs/zero/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#4 /Applications/MAMP/htdocs/zero/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#5 /Applications/MAMP/htdocs/zero/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#6 /Applications/MAMP/htdocs/zero/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#7 /Applications/MAMP/htdocs/zero/app/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save(Array)
#8 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
#9 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/zero/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/zero/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /Applications/MAMP/htdocs/zero/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-08-01 03:52:51 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: POST, Route: cadastro]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 3 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 7 APPPATH/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
 9 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-01 03:54:31 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /Applications/MAMP/htdocs/zero/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Applications/MAMP/htdocs/zero/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Applications/MAMP/htdocs/zero/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Applications/MAMP/htdocs/zero/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#7 /Applications/MAMP/htdocs/zero/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 /Applications/MAMP/htdocs/zero/app/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save(Array)
#9 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
#10 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/zero/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/zero/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Applications/MAMP/htdocs/zero/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-08-01 03:54:31 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: cadastro]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-01 03:54:31 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$9WFcvPyOjZOfPEsemzmjdObkek3KYLTJQTNoLsVtRkZxxowkZ48Ym\', \'2024-08-01 03:54:31\', \'2024-08-01 03:54:31\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$9WFcvPyOjZOfPEsemzmjdObkek3KYLTJQTNoLsVtRkZxxowkZ48Ym\', \'2024-08-01 03:54:31\', \'2024-08-01 03:54:31\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-01 03:54:31 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$9WFcvPyOjZOfPEsemzmjdObkek3KYLTJQTNoLsVtRkZxxowkZ48Ym\', \'2024-08-01 03:54:31\', \'2024-08-01 03:54:31\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$9WFcvPyOjZOfPEsemzmjdObkek3KYLTJQTNoLsVtRkZxxowkZ48Ym\', \'2024-08-01 03:54:31\', \'2024-08-01 03:54:31\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$9WFcvPyOjZOfPEsemzmjdObkek3KYLTJQTNoLsVtRkZxxowkZ48Ym\', \'2024-08-01 03:54:31\', \'2024-08-01 03:54:31\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
11 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-01 03:54:37 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /Applications/MAMP/htdocs/zero/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Applications/MAMP/htdocs/zero/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Applications/MAMP/htdocs/zero/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Applications/MAMP/htdocs/zero/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#7 /Applications/MAMP/htdocs/zero/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 /Applications/MAMP/htdocs/zero/app/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save(Array)
#9 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
#10 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/zero/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/zero/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Applications/MAMP/htdocs/zero/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-08-01 03:54:37 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: cadastro]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-01 03:54:37 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$jsqwwu5oTopYyugRgcGbs.1QLLJKVhbhD1qLIIY0BlENpI/0orZKu\', \'2024-08-01 03:54:37\', \'2024-08-01 03:54:37\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$jsqwwu5oTopYyugRgcGbs.1QLLJKVhbhD1qLIIY0BlENpI/0orZKu\', \'2024-08-01 03:54:37\', \'2024-08-01 03:54:37\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-01 03:54:37 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$jsqwwu5oTopYyugRgcGbs.1QLLJKVhbhD1qLIIY0BlENpI/0orZKu\', \'2024-08-01 03:54:37\', \'2024-08-01 03:54:37\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$jsqwwu5oTopYyugRgcGbs.1QLLJKVhbhD1qLIIY0BlENpI/0orZKu\', \'2024-08-01 03:54:37\', \'2024-08-01 03:54:37\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$jsqwwu5oTopYyugRgcGbs.1QLLJKVhbhD1qLIIY0BlENpI/0orZKu\', \'2024-08-01 03:54:37\', \'2024-08-01 03:54:37\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
11 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-01 03:54:45 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'mamp'@'localhost' (using password: YES) in /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'mamp', Object(SensitiveParameterValue), 'zero', 3306, '', 0)
#1 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/zero/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Applications/MAMP/htdocs/zero/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Applications/MAMP/htdocs/zero/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Applications/MAMP/htdocs/zero/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#7 /Applications/MAMP/htdocs/zero/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 /Applications/MAMP/htdocs/zero/app/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save(Array)
#9 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
#10 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/zero/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/zero/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Applications/MAMP/htdocs/zero/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/zero/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 /Applications/MAMP/htdocs/zero/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#4 /Applications/MAMP/htdocs/zero/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#5 /Applications/MAMP/htdocs/zero/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#6 /Applications/MAMP/htdocs/zero/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#7 /Applications/MAMP/htdocs/zero/app/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save(Array)
#8 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
#9 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/zero/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/zero/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /Applications/MAMP/htdocs/zero/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-08-01 03:54:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: cadastro]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 3 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 7 APPPATH/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
 9 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-01 03:54:53 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /Applications/MAMP/htdocs/zero/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Applications/MAMP/htdocs/zero/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Applications/MAMP/htdocs/zero/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Applications/MAMP/htdocs/zero/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#7 /Applications/MAMP/htdocs/zero/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 /Applications/MAMP/htdocs/zero/app/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save(Array)
#9 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
#10 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/zero/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/zero/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Applications/MAMP/htdocs/zero/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-08-01 03:54:53 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: cadastro]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-01 03:54:53 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$ucFE0V5Ry.ynZQF7nZXmZuT.XUxJUobBskM/KyOj9N.sF8qhW2u26\', \'2024-08-01 03:54:53\', \'2024-08-01 03:54:53\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$ucFE0V5Ry.ynZQF7nZXmZuT.XUxJUobBskM/KyOj9N.sF8qhW2u26\', \'2024-08-01 03:54:53\', \'2024-08-01 03:54:53\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-01 03:54:53 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$ucFE0V5Ry.ynZQF7nZXmZuT.XUxJUobBskM/KyOj9N.sF8qhW2u26\', \'2024-08-01 03:54:53\', \'2024-08-01 03:54:53\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$ucFE0V5Ry.ynZQF7nZXmZuT.XUxJUobBskM/KyOj9N.sF8qhW2u26\', \'2024-08-01 03:54:53\', \'2024-08-01 03:54:53\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$ucFE0V5Ry.ynZQF7nZXmZuT.XUxJUobBskM/KyOj9N.sF8qhW2u26\', \'2024-08-01 03:54:53\', \'2024-08-01 03:54:53\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
11 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-01 03:56:51 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /Applications/MAMP/htdocs/zero/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Applications/MAMP/htdocs/zero/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Applications/MAMP/htdocs/zero/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Applications/MAMP/htdocs/zero/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#7 /Applications/MAMP/htdocs/zero/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 /Applications/MAMP/htdocs/zero/app/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save(Array)
#9 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
#10 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/zero/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/zero/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Applications/MAMP/htdocs/zero/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-08-01 03:56:51 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: cadastro]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-01 03:56:51 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$6rGzs5U60QKYtryrOr6VxONxYzzw4ePookuTIs4OWjuehQZO0iad6\', \'2024-08-01 03:56:51\', \'2024-08-01 03:56:51\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$6rGzs5U60QKYtryrOr6VxONxYzzw4ePookuTIs4OWjuehQZO0iad6\', \'2024-08-01 03:56:51\', \'2024-08-01 03:56:51\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-01 03:56:51 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$6rGzs5U60QKYtryrOr6VxONxYzzw4ePookuTIs4OWjuehQZO0iad6\', \'2024-08-01 03:56:51\', \'2024-08-01 03:56:51\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$6rGzs5U60QKYtryrOr6VxONxYzzw4ePookuTIs4OWjuehQZO0iad6\', \'2024-08-01 03:56:51\', \'2024-08-01 03:56:51\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$6rGzs5U60QKYtryrOr6VxONxYzzw4ePookuTIs4OWjuehQZO0iad6\', \'2024-08-01 03:56:51\', \'2024-08-01 03:56:51\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
11 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-01 03:56:54 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Applications/MAMP/htdocs/zero/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /Applications/MAMP/htdocs/zero/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /Applications/MAMP/htdocs/zero/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Applications/MAMP/htdocs/zero/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Applications/MAMP/htdocs/zero/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Applications/MAMP/htdocs/zero/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, false)
#7 /Applications/MAMP/htdocs/zero/system/BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 /Applications/MAMP/htdocs/zero/app/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save(Array)
#9 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
#10 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/zero/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/zero/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/zero/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Applications/MAMP/htdocs/zero/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-08-01 03:56:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: cadastro]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-01 03:56:54 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$3SxHuU/NrO.9ZW/RyeJLqOCSLW2BIFRXd5.Hf1tfZDQT8BWNpVjm2\', \'2024-08-01 03:56:54\', \'2024-08-01 03:56:54\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$3SxHuU/NrO.9ZW/RyeJLqOCSLW2BIFRXd5.Hf1tfZDQT8BWNpVjm2\', \'2024-08-01 03:56:54\', \'2024-08-01 03:56:54\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-01 03:56:54 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$3SxHuU/NrO.9ZW/RyeJLqOCSLW2BIFRXd5.Hf1tfZDQT8BWNpVjm2\', \'2024-08-01 03:56:54\', \'2024-08-01 03:56:54\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$3SxHuU/NrO.9ZW/RyeJLqOCSLW2BIFRXd5.Hf1tfZDQT8BWNpVjm2\', \'2024-08-01 03:56:54\', \'2024-08-01 03:56:54\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'srbv1965@gmail.com\', \'edersonbastiani@gmail.com\', \'$2y$10$3SxHuU/NrO.9ZW/RyeJLqOCSLW2BIFRXd5.Hf1tfZDQT8BWNpVjm2\', \'2024-08-01 03:56:54\', \'2024-08-01 03:56:54\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH/BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH/Controllers/AuthController.php(33): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->cadastrar()
11 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-01 04:20:03 --> ErrorException: Array to string conversion
[Method: POST, Route: login]
in APPPATH/Controllers/AuthController.php on line 61.
 1 APPPATH/Controllers/AuthController.php(61): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', '/Applications/MAMP/htdocs/zero/app/Controllers/AuthController.php', 61)
 2 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->realizarLogin()
 3 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 4 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-01 04:20:51 --> ParseError: syntax error, unexpected token "}"
[Method: POST, Route: login]
in APPPATH/Controllers/AuthController.php on line 67.
 1 SYSTEMPATH/Autoloader/Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('/Applications/MAMP/htdocs/zero/app/Controllers/AuthController.php')
 2 SYSTEMPATH/Autoloader/Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\AuthController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\AuthController')
 4 SYSTEMPATH/CodeIgniter.php(887): class_exists('\\App\\Controllers\\AuthController', true)
 5 SYSTEMPATH/CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-08-01 04:23:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-08-01 04:25:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-08-01 04:27:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-08-01 04:29:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-08-01 04:29:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-08-01 04:30:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-08-01 04:31:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-08-01 04:31:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-08-01 17:42:46 --> Error: Class "App\Models\UserModel" not found
[Method: POST, Route: cadastro]
in APPPATH\Controllers\AuthController.php on line 26.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->realizarCadastro()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-08-01 17:58:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
